---
- name: Install epel
  package:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present

- name: Install fish
  package:
    name: fish
    state: present

- name: Create fish demo user
  user:
    name: demo
    shell: /usr/bin/fish
